[package]
name = "hone"
version = "0.1.0"
authors = ["uzushino <torattoria.mamiya@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
diesel = { version = "1.3.3", features = ["sqlite"] }
diesel_migrations = "1.3.0"